name = "chain-gateway-cron-worker"
main = "./build/worker.mjs"
compatibility_date = "2024-04-15"
workers_dev = false


[build]
command = "make build"

[[d1_databases]]
binding = "DB"
database_name = "chain-gateway"
database_id = ""

[[queues.producers]]
queue = "gateway-checker"
binding = "QUEUE"


[triggers]
crons = ["*/2 * * * *"]