// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type CheckRule struct {
	ID        int64  `json:"id"`
	ChainID   string `json:"chain_id"`
	Source    string `json:"source"`
	Rules     string `json:"rules"`
	CreatedAt int64  `json:"created_at"`
}

type KvCache struct {
	ID        int64  `json:"id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	CreatedAt int64  `json:"created_at"`
}

type ReadyUpstream struct {
	ID        int64  `json:"id"`
	ChainID   string `json:"chain_id"`
	Source    string `json:"source"`
	Rpc       string `json:"rpc"`
	CreatedAt int64  `json:"created_at"`
}

type SecretKey struct {
	ID           int64  `json:"id"`
	AccessKey    string `json:"access_key"`
	SecretKey    string `json:"secret_key"`
	Service      string `json:"service"`
	Group        string `json:"group"`
	CreatedAt    int64  `json:"created_at"`
	AllowOrigins string `json:"allow_origins"`
	AllowIps     string `json:"allow_ips"`
}

type Upstream struct {
	ID        int64  `json:"id"`
	ChainID   string `json:"chain_id"`
	Source    string `json:"source"`
	Rpc       string `json:"rpc"`
	CreatedAt int64  `json:"created_at"`
}
