name = "chain-gateway-proxy-worker"
main = "./build/worker.mjs"
compatibility_date = "2024-04-15"
# logpush = true
workers_dev = true

routes = [
  { pattern = "chain-gateway.{your-subdomain}", custom_domain = true }
]

# tail_consumers = [{service = "log-worker"}]

[[d1_databases]]
binding = "DB"
database_name = "chain-gateway"
database_id = ""

[build]
command = "make build"

[observability]
enabled = false
head_sampling_rate = 1
