name = "chain-gateway-admin-worker"
main = "./build/worker.mjs"
compatibility_date = "2024-04-15"

[[d1_databases]]
binding = "DB"
database_name = "chain-gateway"
database_id = ""

[build]
command = "make build"

[[queues.producers]]
queue = "gateway-checker"
binding = "QUEUE"