// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Config struct {
	ID      int64  `json:"id"`
	Key     string `json:"key"`
	Value   string `json:"value"`
	Module  string `json:"module"`
	Created int64  `json:"created"`
	Updated int64  `json:"updated"`
}

type ReadyUpstream struct {
	ID      int64  `json:"id"`
	ChainID string `json:"chain_id"`
	Source  string `json:"source"`
	Rpc     string `json:"rpc"`
	Created int64  `json:"created"`
	Updated int64  `json:"updated"`
}

type SecretKey struct {
	ID           int64  `json:"id"`
	AccessKey    string `json:"access_key"`
	SecretKey    string `json:"secret_key"`
	Service      string `json:"service"`
	Group        string `json:"group"`
	AllowOrigins string `json:"allow_origins"`
	AllowIps     string `json:"allow_ips"`
	RouteRules   string `json:"route_rules"`
	Created      int64  `json:"created"`
	Updated      int64  `json:"updated"`
}
