// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createConfig = `-- name: CreateConfig :execresult
INSERT INTO config (
  ` + "`" + `key` + "`" + `, ` + "`" + `value` + "`" + `, module, created, updated
) VALUES (
  ?, ?, ?, ?, ?
)
`

type CreateConfigParams struct {
	Key     string `json:"key"`
	Value   string `json:"value"`
	Module  string `json:"module"`
	Created int64  `json:"created"`
	Updated int64  `json:"updated"`
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createConfig,
		arg.Key,
		arg.Value,
		arg.Module,
		arg.Created,
		arg.Updated,
	)
}

const createReadyUpstream = `-- name: CreateReadyUpstream :execresult
INSERT INTO ready_upstream (
  chain_id, source, rpc, created, updated
) VALUES (
  ?, ?, ?, ?, ?
)
`

type CreateReadyUpstreamParams struct {
	ChainID string `json:"chain_id"`
	Source  string `json:"source"`
	Rpc     string `json:"rpc"`
	Created int64  `json:"created"`
	Updated int64  `json:"updated"`
}

func (q *Queries) CreateReadyUpstream(ctx context.Context, arg CreateReadyUpstreamParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReadyUpstream,
		arg.ChainID,
		arg.Source,
		arg.Rpc,
		arg.Created,
		arg.Updated,
	)
}

const createSecretKey = `-- name: CreateSecretKey :execresult
INSERT INTO secret_key (
  access_key, secret_key, ` + "`" + `service` + "`" + `, ` + "`" + `group` + "`" + `, allow_origins, allow_ips, route_rules, created, updated
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateSecretKeyParams struct {
	AccessKey    string `json:"access_key"`
	SecretKey    string `json:"secret_key"`
	Service      string `json:"service"`
	Group        string `json:"group"`
	AllowOrigins string `json:"allow_origins"`
	AllowIps     string `json:"allow_ips"`
	RouteRules   string `json:"route_rules"`
	Created      int64  `json:"created"`
	Updated      int64  `json:"updated"`
}

func (q *Queries) CreateSecretKey(ctx context.Context, arg CreateSecretKeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSecretKey,
		arg.AccessKey,
		arg.SecretKey,
		arg.Service,
		arg.Group,
		arg.AllowOrigins,
		arg.AllowIps,
		arg.RouteRules,
		arg.Created,
		arg.Updated,
	)
}

const getConfigByKey = `-- name: GetConfigByKey :one
SELECT id, ` + "`" + `key` + "`" + `, value, module, created, updated FROM config 
WHERE ` + "`" + `key` + "`" + ` = ? AND module = ?
`

type GetConfigByKeyParams struct {
	Key    string `json:"key"`
	Module string `json:"module"`
}

func (q *Queries) GetConfigByKey(ctx context.Context, arg GetConfigByKeyParams) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfigByKey, arg.Key, arg.Module)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Module,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getReadyUpstreamByChainIdSource = `-- name: GetReadyUpstreamByChainIdSource :one
SELECT id, chain_id, source, rpc, created, updated FROM ready_upstream 
WHERE chain_id = ? AND source = ?
`

type GetReadyUpstreamByChainIdSourceParams struct {
	ChainID string `json:"chain_id"`
	Source  string `json:"source"`
}

func (q *Queries) GetReadyUpstreamByChainIdSource(ctx context.Context, arg GetReadyUpstreamByChainIdSourceParams) (ReadyUpstream, error) {
	row := q.db.QueryRowContext(ctx, getReadyUpstreamByChainIdSource, arg.ChainID, arg.Source)
	var i ReadyUpstream
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Source,
		&i.Rpc,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getSecretKeyByAccessKey = `-- name: GetSecretKeyByAccessKey :one
SELECT id, access_key, secret_key, service, ` + "`" + `group` + "`" + `, allow_origins, allow_ips, route_rules, created, updated FROM secret_key 
WHERE access_key = ?
`

func (q *Queries) GetSecretKeyByAccessKey(ctx context.Context, accessKey string) (SecretKey, error) {
	row := q.db.QueryRowContext(ctx, getSecretKeyByAccessKey, accessKey)
	var i SecretKey
	err := row.Scan(
		&i.ID,
		&i.AccessKey,
		&i.SecretKey,
		&i.Service,
		&i.Group,
		&i.AllowOrigins,
		&i.AllowIps,
		&i.RouteRules,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listReadyUpstreamsByChainId = `-- name: ListReadyUpstreamsByChainId :many
SELECT id, chain_id, source, rpc, created, updated FROM ready_upstream 
WHERE chain_id = ?
`

func (q *Queries) ListReadyUpstreamsByChainId(ctx context.Context, chainID string) ([]ReadyUpstream, error) {
	rows, err := q.db.QueryContext(ctx, listReadyUpstreamsByChainId, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadyUpstream
	for rows.Next() {
		var i ReadyUpstream
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.Source,
			&i.Rpc,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretKeys = `-- name: ListSecretKeys :many
SELECT id, access_key, secret_key, service, ` + "`" + `group` + "`" + `, allow_origins, allow_ips, route_rules, created, updated FROM secret_key
`

func (q *Queries) ListSecretKeys(ctx context.Context) ([]SecretKey, error) {
	rows, err := q.db.QueryContext(ctx, listSecretKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecretKey
	for rows.Next() {
		var i SecretKey
		if err := rows.Scan(
			&i.ID,
			&i.AccessKey,
			&i.SecretKey,
			&i.Service,
			&i.Group,
			&i.AllowOrigins,
			&i.AllowIps,
			&i.RouteRules,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfigValue = `-- name: UpdateConfigValue :execresult
UPDATE config SET ` + "`" + `value` + "`" + ` = ?, updated = ? 
WHERE ` + "`" + `key` + "`" + ` = ? AND module = ?
`

type UpdateConfigValueParams struct {
	Value   string `json:"value"`
	Updated int64  `json:"updated"`
	Key     string `json:"key"`
	Module  string `json:"module"`
}

func (q *Queries) UpdateConfigValue(ctx context.Context, arg UpdateConfigValueParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateConfigValue,
		arg.Value,
		arg.Updated,
		arg.Key,
		arg.Module,
	)
}

const updateReadyUpstreamRpc = `-- name: UpdateReadyUpstreamRpc :execresult
UPDATE ready_upstream SET rpc = ?, updated = ? 
WHERE chain_id = ? AND source = ?
`

type UpdateReadyUpstreamRpcParams struct {
	Rpc     string `json:"rpc"`
	Updated int64  `json:"updated"`
	ChainID string `json:"chain_id"`
	Source  string `json:"source"`
}

func (q *Queries) UpdateReadyUpstreamRpc(ctx context.Context, arg UpdateReadyUpstreamRpcParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateReadyUpstreamRpc,
		arg.Rpc,
		arg.Updated,
		arg.ChainID,
		arg.Source,
	)
}

const updateSecretKey = `-- name: UpdateSecretKey :execresult
UPDATE secret_key SET ` + "`" + `group` + "`" + ` = ?, ` + "`" + `service` + "`" + ` = ?, allow_origins = ?, allow_ips = ?, route_rules = ?, updated = ?
WHERE access_key = ?
`

type UpdateSecretKeyParams struct {
	Group        string `json:"group"`
	Service      string `json:"service"`
	AllowOrigins string `json:"allow_origins"`
	AllowIps     string `json:"allow_ips"`
	RouteRules   string `json:"route_rules"`
	Updated      int64  `json:"updated"`
	AccessKey    string `json:"access_key"`
}

func (q *Queries) UpdateSecretKey(ctx context.Context, arg UpdateSecretKeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSecretKey,
		arg.Group,
		arg.Service,
		arg.AllowOrigins,
		arg.AllowIps,
		arg.RouteRules,
		arg.Updated,
		arg.AccessKey,
	)
}
